### ISSUE TITLE
Log response errors via LoggerInterface

### ISSUE THREAD

**Issue by loncar** [facebook/facebook-php-business-sdk#273]
I have notice that Api class is not logging the error responses due to :

  ```
/**
   * @param RequestInterface $request
   * @return ResponseInterface
   */
  public function executeRequest(RequestInterface $request) {
    $this->getLogger()->logRequest('debug', $request);
    $response = $request->execute();
    $this->getLogger()->logResponse('debug', $response);

    return $response;
  }
```
and in case of thrown error logResponse will never be called. Can that be changed so the response object is still there and error is thrown after logging resonse?

It will be useful to handle error logging and all logging from one place and not be forced to put logging inside every try/catch regarding all API calls.

Thanks

**Comment by lintaocui** [comment]
@loncar thanks for the suggestion. We will consider it.

**Comment by thomhickey** [comment]
+1 for this request because added to that is the fact that error messages often times do not include information from the request that is vital to stitching things together. For example:

{"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_subcode":1487056,"is_transient":false,"error_user_title":"Can't Edit Ad Set","error_user_msg":"You can only edit active or paused ad sets. Once an ad set has been marked as deleted, you can only change the name.","fbtrace_id":"DeV4WEKfidJ"}}%

I have nothing here to stitch back to the request (e.g. the AdSet's ID) and - as @loncar mentioned - since I am logging exceptions in catch blocks I have no way to either a) log to the same log file as the CurlLogger or b) pull data from the request so that my exception log has enough information to debug the problem. Instead I have to rely on my application data but I would much rather see what the sdk actually sent to and received from the API.

**Comment by jamespshields** [comment]
+1

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
