### ISSUE TITLE
Call to undefined method FacebookAds\Object\AdCreative::deleteSelf()

### ISSUE THREAD

**Issue by biscolab** [facebook/facebook-php-business-sdk#385]
As suggested by the official documentation at [https://developers.facebook.com/docs/marketing-api/reference/ad-creative](https://developers.facebook.com/docs/marketing-api/reference/ad-creative) page I get the following error: Call to undefined method FacebookAds\Object\AdCreative::deleteSelf().
I had to replace it with `delete()` method:
```php
$creative = new AdCreative(<adcreative_id>);
$creative->delete();
```
It works!

**Comment by bilaliqbal-te** [comment]
Facing almost same issue, but for my case `delete()` method throwing undefined method exception. While getting this error with `deleteSelf()`
"You cannot delete this creative because it is currently in use for existing adgroups."

What I was trying is to replace Ad Creative with old one (having updated data for url_tags field). Any suggestion, how could I fix this problem and able to replace Ad Creative with the new one?

**Comment by jingping2015** [comment]
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.
