### ISSUE TITLE
Can't create a saved Audience using graph API progrmitically

### ISSUE THREAD

**Issue by poornesh-sharma** [facebook/facebook-php-business-sdk#491]
When using the UI you can create fantastic "saved audiences" that allow you to assign interests, locations (cities, countries, even zip codes) and other inclusions/exclusions.

This is great! But I want to do this programmatically!

Right now it seems you cannot.. unless I am missing something?

There was a similar ticket created and it was closed saying something like 
"Java SDK is updated and asked to repro the issue"

But I do not see any direct API to create a saved_audience programmatically

**Comment by codytwinton** [comment]
Since we want to handle bugs more efficiently, we've decided to close issue reporting in Github and move to our dedicated bug reporting channel. If you encounter a bug with Business SDK (PHP), please report the issue at [our developer bug reporting channel](https://developers.facebook.com/support/bugs/).
